Makefile
Updates the Makefile to make it possible to install bitlbee-discord into the specified `DESTDIR`, defaulting to /usr/lib64/bitlbee.
Makes it possible to create Arch Linux PKGBUILDs.
=> Update Makefile to install into DESTDIR

src/discord-handlers.c
A somewhat new feature to discord allows users the option to rename themselves on a server by server basis.
When a user using the web or desktop app mentions a renamed user a ! is prepended to their user id and looks something like this (via bitlbee)
```<@!123456789> test too```
after adjusting the regex pattern it shows the username thats linked to the user's id (not the renamed nick)
```@mumixam test too```
when desktop and webapp would display
```@renamed test too```
This may not the ideal fix you want but its alot better than a big integer.
This bug was found and fixed by a member of beecord
=> fix for error when displaying username of a renamed user

README, src/discord.c
* In ```discord.c``` plugin info, 'bitlbee-discrod' → 'bitlbee-discord'
* In ```README```, fix a few minor typos
=> Fix minor typos in plugin info, README

src/discord-websockets.c
* websockets: use random_bytes() and char arrays instead of guint32
BitlBee's random_bytes() function uses /dev/urandom instead of glib's
mersenne twister, and while the websocket mask isn't really meant for
actual security, this also helps because random_bytes() has a more
convenient interface, working on char arrays.
The signature of discord_ws_mask() had to be changed to take a 4 byte char
array instead of a guint32, but that also removes an awkward cast.
* websockets: Allocate len + 1 to leave a null terminator if needed
Unlikely to be an issue in practice, but who knows.
=> Couple of minor fixes in discord-websockets

src/discord-http.c
When I first tried this plugin I was unable to connect to Discord.  There weren't any error messages.  After playing around with cURL and Wireshark i found something interesting.
$ curl -q -X POST -d '{}' -H Content-Type:application/json http://discordapp.com/api/auth/login
<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx</center>
</body>
</html>
$ curl -qL -X POST -d '{}' -H Content-Type:application/json http://discordapp.com/api/auth/login
<!DOCTYPE html>
<html lang=en>
<meta charset=utf-8>
<meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
<title>Error 411 (Length Required)!!1</title>
<style>
*{margin:0;padding:0}html,code{font:15px/22px …
=> Use HTTPS instead of HTTP

src/discord-handlers.c, src/discord-handlers.h, src/discord-http.c, src/discord-http.h, src/discord-util.c, src/discord-websockets.c, src/discord.h
This is unfortunate (given the somewhat generic header names) but that's how it should be used to support non-system-wide installs.
With the previous include set up, building this plugin only worked when bitlbee's headers were in `/usr/include/bitlbee`, because `/usr/include` is in the default include path and the `-I/usr/include/bitlbee` is unused (because `/usr/include/bitlbee/bitlbee` does not exist)
Likely related to #77
=> Change bitlbee includes from <bitlbee/*.h> to <*.h>

src/Makefile.am
Quoting https://cygwin.com/ml/cygwin/2013-07/msg00421.html
>despite popular misconception, this flag is harmless on non-PE targets
This also depends on changes on the bitlbee side to be able to link to
bitlbee itself, see bitlbee commit 54b2a367 (version string
3.5.1+20170513+develop+16-g54b2a367-git)
=> Makefile.am: add -no-undefined for cygwin

src/Makefile.am
This reverts commit 84315b6bfc5fdc5fe631f29d85113b52abb2936a.
Turns out it wasn't harmless, and it breaks mac OS. Instead of adding
platform checks here, this flag is now included in the cygwin-specific
parts of the bitlbee pkg-config file, as of bitlbee commit b9c10a1a
(version string 3.5.1+20170529+develop+18-gb9c10a1a-git)
-----
Sorry for the noise.
=> Revert "Makefile.am: add -no-undefined for cygwin"

src/discord-handlers.c, src/discord-util.c, src/discord-util.h
Fixes issues with invalid utf8 in servers that start their names with
unicode characters (like emoji)
Oddly enough there's no glib function for this, and bitlbee's
truncate_utf8() does the opposite of what we need to do here (truncates
by bytes instead of characters and ensures those bytes are valid utf8)
------
Fixes #85 
I should probably figure out what to do to avoid writing invalid utf8 to the config in the first place (like some sort of write-time validation? but what can i do if it's not valid?), but that's harder than fixing this side.
=> Make server_prefix_len truncate by utf8 characters instead of bytes

src/discord-handlers.c, src/discord-http.c, src/discord-util.c, src/discord.c, src/discord.h
Messages sent from another discord client will now appear as if you sent
them from Bitlbee.
See https://wiki.bitlbee.org/SelfMessages for more information about
this feature.
=> Enable self messages

src/discord-websockets.c
We could end up in a situation where websocket messages would stay stuck
in the SSL buffer because we only read one at a time although the SSL
buffer can hold more.
This addresses the sync issues I mentioned in #104
=> Read all available data from the SSL buffer

src/discord-handlers.c
- Fix login failure when no servers exist
- ~~Send sync requests together
The gateway will sometimes ignore two consecutive sync requests.~~
~~This makes sure to send only one request for all the servers that we
need to sync.~~
EDIT: Actually, the second issue isn't fixed at all, I'll have to investigate more
EDIT2: See #105
=> Fix login failure when no servers exist

src/discord-handlers.c
Perhaps add an option in future to suppress the URL, but it's kind of nice for clients that embed image URLs (if a little noisy)
Note: I am not a C programmer, please review this carefully for buffer overflows, use after frees, null pointer exceptions and other things I don't really understand.
I built and tested it works at least.
=> Convert custom emoji to the code and URL

src/discord-handlers.c
Occasionally the gateway will request a heartbeat, and the client must respond otherwise you'll be logged out and get `OPCODE_INVALID_SESSION`, requiring a reconnect to get everything working again (in this state you appear offline and receive no messages, but are still able to send outgoing messages). It's pretty common and happens to me multiple times per day when DMing with friends. Possibly related to #95?
This PR triggers a reconnect when requested, and also handles the heartbeat request so it doesn't happen in the first place!
=> Heartbeat and reconnect opcodes

src/discord-websockets.c
Turns out Discord changed the [Status Update Structure](https://discordapp.com/developers/docs/topics/gateway#update-status-gateway-status-update-structure) and [Game Object](https://discordapp.com/developers/docs/topics/gateway#game-object) objects; status/afk are now mandatory, games now require a type, and idle_since was renamed to since and changed to milliseconds.
Sending old-style messages causes immediate disconnection. Strange how Discord changed that without bumping API version, but their entire setup is weird.
Either way, the fix is simple: let's send new-style status messages instead.
e: Fixes #120
=> Update away status handler

src/discord-handlers.c, src/discord-handlers.h, src/discord-websockets.c
I got a few segfaults during a recent Discord outage. Throwing Valgrind at it yielded:
```
[23:25:36] <<< ((null)) discord_parse_message 36
{"t":null,"s":null,"op":9,"d":false}
==20729== Invalid read of size 8
==20729==    at 0x8683E84: discord_ws_in_cb (discord-websockets.c:247)
==20729==    by 0x130FD0: ??? (in /usr/sbin/bitlbee)
==20729==    by 0x566359F: event_base_loop (in /usr/lib/x86_64-linux-gnu/libevent-2.0.so.5.1.9)
==20729==    by 0x130B4F: b_main_run (in /usr/sbin/bitlbee)
==20729==    by 0x11AD3C: main (in /usr/sbin/bitlbee)
==20729==  Address 0x80ff9e8 is 88 bytes inside a block of size 136 free'd
==20729==    at 0x4C2CDDB: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==20729==    by 0x867F2BC: discord_logout (discord.c:139)
==20729==    by 0x13D6D1: …
```
=> Fix use-after-free on OPCODE_RECONNECT/INVALID_SESSION

README, contrib/docker/Dockerfile, contrib/docker/bitlbee.conf
I had to fix some permissions problems that weren't obvious when I first started running it. I also added a line to the readme and switched bitlbee mode to the ForkDaemon, which is preferred as a crash in for one user doesn't crash the whole server.
=> Tweak contrib/docker; fix permissions, enhance readme, change to ForkDaemon

src/discord.c
To reproduce:
- /part #general
- /msg &bitlbee channel #general del
- Wait a few minutes
Expected: I don't see that channel again
Actual:
```
[22:56:27] <<< (Alcaro) discord_parse_message 274
{"t":"PRESENCE_UPDATE","s":47,"op":0,"d":{"user":{"id":"313409368643338251"},"status":"online","roles":["280006158192869376","308737073496719362"],"nick":null,"guild_id":"161245277179609089","game":{"type":0,"timestamps":{"start":1524430585163},"name":"Warframe Launcher"}}}
Program received signal SIGSEGV, Segmentation fault.
0x00005555555700e9 in irc_channel_add_user ()
(gdb) bt
#0  0x00005555555700e9 in irc_channel_add_user ()
#1  0x000055555556cc5f in ?? ()
#2  0x0000555555587a74 in imcb_chat_add_buddy ()
#3  0x00007ffff478c05d in discord_handle_presence (ic=0x555555804c50, 
pinfo=<optimized out>, …
```
=> Fix crash when deleting a channel

src/discord-handlers.c
Using the official client, say :thonk::thonk: in any channel.
Result: \<Alcaro> :thonk: https://cdn.discordapp.com/emojis/379295935689392148.png:thonk: https://cdn.discordapp.com/emojis/379295935689392148.png, where the :thonk is considered part of the URL, which makes it leads nowhere (some clients consider the final : part of the URL too, but that doesn't work either).
The simplest fix is this tweak to the emote regexes; regexes are greedy, so this won't emit duplicate spaces. It does yield an extra space at the end if a message ends with an emote, which can be avoided by doubling the number of regexes, but that's a bit of extra code for questionable gains. Your choice if it's worth it.
=> Enforce space after emote URLs

src/discord-handlers.c, src/discord-handlers.h, src/discord-http.c, src/discord-util.c, src/discord-util.h
Improves #152, but I wouldn't consider it fully fixed until bitlbee/bitlbee#98 (or equivalent) is done. Your choice if it's good enough that #152 can be closed.
strptime isn't part of the C standard library, but it is [part of POSIX](http://pubs.opengroup.org/onlinepubs/009695399/functions/strptime.html); since manual mentions 'sudo make install', I suspect non-Unix isn't supported. If that's incorrect, I can check if GLib contains a date parser, we already have a dependency on that.
Finally, bitlbee dev docs suck.
=> Add timestamp support

src/Makefile.am
Fixes #156
The obvious fix would be renaming that variable, but adding -std=c99 instead has two advantages: It makes sure nobody else runs into similar traps later, and it improves compatibility with old compilers that default to -std=gnu89 and fail on variable declarations in for loops. (Modern GCCs default to -std=gnu11.)
Could use -std=c11 instead, but unless we're using C11 features, using C11 seems pointless.
=> Compile as C99

src/discord-websockets.c, src/discord-websockets.h, src/discord.c
You can set your discord status to 'online', 'dnd', 'idle', or 'invisible' via `away` variable's value.
**Known issues**: 
- bitlbee seems to discard `status` variable's value (`msg`, `message` in the code) if `away` variable is not empty. This mean's you can't change what your "current game" is unless you have your away status empty.
- ~~`"afk": true` means you should receive push notifications regardless of away status.~~
- People using Quassel might have away status not set to "Idle" when the plugin is provided with a nonstandard away value. (#25)?
These changes are experimental, feel free to suggest feedback before merging to mainline.
=> Set away status

src/discord-util.c
Going backwards through the list of optimizations applied - this is the last one, only meaningful after applying a bunch of others. It's also trivial so, worth splitting.
See the left side of this:
=> discord_canonize_name: Use str_reject_chars from bitlbee instead of a regex

src/discord-http.c
After seeing this error, I've often found myself opening the other client and checking all over for what messages I've sent and whether any is missing (half of the time, it's none of them; discord often delivers the message, but returns some random error over http. I suspect this is what causes all those duplicate messages on the other client).
Let's simplify that by telling which message is relevant.
This doesn't tell what channel it's for, and leaves `<@12345678>`/etc in there. This can be fixed later, but let's start simple; this is sufficient to allow identifying which message is screwing up and verifying whether it arrived.
(also yes, that strstr is ugly. I'd be glad to replace it with something else, but I couldn't find anything better.)
=> Let's tell what message failed to send

src/discord-handlers.c
Before these fixes, RELATIONSHIP_REMOVE would cause a segfault. My understanding of this, is that RELATIONSHIP_REMOVE's json looks like: `{"t":"RELATIONSHIP_REMOVE","s":97,"op":0,"d":{"type":1,"id":"<removed>"}}` and this is the primary cause of this problem.
In the original code, `json_value *uinfo = json_o_get(rinfo, "user");` would lead to a null pointer being fed into discord_canonize_name as `char *name = discord_canonize_name(json_o_str(uinfo, "username"));` has no handling for being fed a null pointer. This then causes a segmentation fault, as follows:
```
Program received signal SIGSEGV, Segmentation fault.
0x000055555558cd4b in str_reject_chars (string=0x0, reject=0x7ffff7fc90c6 "@+ ", replacement=95 '_') at misc.c:741
741		while (*c) {
#0  0x000055555558cd4b in str_reject_chars …
```
=> Added fixes for crashing upon somebody removing you from their friends.

src/discord-handlers.c
I think this is caused by uinf and uinf->user being a null pointer. Not really sure why that is, but this fixes the crash that would otherwise cause. I imagine it's because the user has never actually existed within the bitlbee user list and therefore doesn't need updating, but the real question is why it works for the first rejection but not the second.
I also slightly cleaned it up so uinf is defined before usage in either case, meaning there's only one definition statement.
```
Program received signal SIGSEGV, Segmentation fault.
discord_handle_relationship (ic=0x5555557fab50, rinfo=0x5555558121d0, action=ACTION_DELETE) at discord-handlers.c:223
223	    name = g_strdup_printf(uinf->name);
#0  discord_handle_relationship (ic=0x5555557fab50, rinfo=0x5555558121d0, action=ACTION_DELETE) at …
```
=> Fixed crashing problems upon rejecting more than one friend request.

src/discord-handlers.c
Users' true (global) names will be available in WHOIS output and in clients that display real names in the chat view, etc.
This is the result of about an hour (maybe 90 minutes?) reading code, trying to understand how BitlBee and the Discord plugin create/maintain users. I think I ultimately found the right place to do this. It compiled & ran nicely on my test Discord account, on my local system, displaying real names in HexChat with all Unicode characters, whitespace, and other nonsense included. (I joined my test account to a fairly large server with ~200 users, many of whom have Discord usernames that BitlBee currently turns into underscore soup.)
This change technically closes #155, assuming it all checks out. I will next look at changing the reported ident as suggested there, if …
=> Set user real name to untouched nickname

src/Makefile.am
This allows people to build on Cygwin.
=> Add BITLBEE_LIBS to discord_la_LDFLAGS
